# Generated by Django 5.2.2 on 2025-06-06 09:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_activity_duration_alter_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='gpx_file',
            field=models.FileField(upload_to=base.models.upload_to_gpx),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_to_profile_images),
        ),
    ]
