# Generated by Django 5.2.2 on 2025-06-09 13:15

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_activity_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=base.models.upload_to_gpx)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField(editable=False)),
                ('moving_time', models.DurationField(editable=False)),
                ('start_time', models.DateTimeField(editable=False)),
                ('end_time', models.DateTimeField(editable=False)),
                ('distance', models.FloatField(editable=False)),
                ('ascent', models.FloatField(editable=False)),
                ('descent', models.FloatField(editable=False)),
                ('avg_speed', models.FloatField(editable=False)),
                ('min_speed', models.FloatField(editable=False)),
                ('max_speed', models.FloatField(editable=False)),
                ('avg_pace', models.FloatField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='gpx_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='base.gpx'),
        ),
    ]
