# Generated by Django 5.2.2 on 2025-06-10 11:14

import datetime
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_gpx_remove_activity_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpx',
            name='ascent',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='avg_pace',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='avg_speed',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='descent',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='min_speed',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='moving_time',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gpx',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='ascent',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_pace',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_speed',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='descent',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(default=datetime.timedelta, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(default=timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_speed',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_speed',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='moving_time',
            field=models.DurationField(default=datetime.timedelta, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='Activity', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=timezone.now, editable=False),
        ),
    ]
