# Generated by Django 5.2.2 on 2025-06-10 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_gpx_ascent_remove_gpx_avg_pace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 11, 16, 8, 289974), editable=False),
        ),
    ]
