# Generated by Django 5.2.3 on 2025-06-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_user_following_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
