# Generated by Django 5.2.3 on 2025-06-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_following_user_id_userfollowing_following_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_following',
        ),
    ]
